### ISSUE TITLE
Auto update not working

### ISSUE THREAD

**Issue by Chilli-RF** [zaafar/poehud_inventorypreview#1]
I remember that in 2.5 it worked, What am I doing wrong?

**Comment by zaafar** [comment]
I will look into it,

**Comment by RuslanRybka** [comment]
I dunno what are you doing wrong. I just open plugins updator and it update me all my plugins and inventorypreview - everything works fine.

**Comment by Chilli-RF** [comment]
I got same issue with map exchange. Need to close and open stash to refresh highlighting.

**Comment by Chilli-RF** [comment]
It was fixed because of HUD update.
