### ISSUE TITLE
Auto Update no longer working

### ISSUE THREAD

**Issue by DetectiveSquirrel** [zaafar/poehud_inventorypreview#2]
Not sure if its just me but auto update no longer working, someone had the issue the other day and i didnt even notice that i had the issue too.

**Comment by zaafar** [comment]
You mean plugins not being updated or poehud isn't being updated?

**Comment by DetectiveSquirrel** [comment]
the inventory isnt being auto updated in the plugin :)
Need to open inventory to make it reload your inventory in the preview.

**Comment by zaafar** [comment]
Oh ur talking about inventory, ok will check it when I go home.
